# 私有源
source 'https://github.com/kaibuleite/xSpecs.git'

use_frameworks!

platform :ios, '9.0'

target 'xAlert_Example' do
  pod 'xAlert', :path => '../'

  target 'xAlert_Tests' do
    inherit! :search_paths

    
  end
end
